#!/bin/sh
#
# $Id: ieee-copyout,v 1.1 2002/09/30 01:18:08 dan Exp $
#
# Copyright (c) 2002 Dan McMahill
# All rights reserved.
#
# This code is derived from software written by Dan McMahill
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#        This product includes software developed by Dan McMahill
#  4. The name of the author may not be used to endorse or promote products
#     derived from this software without specific prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
#  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.
#

#
# This script will be used for creating an archive of the format that
# the IEEE wants for paper submissions
#

echo "$0 has not been completed yet.  Feel free to finish writing"
echo "it and submit the new code."
exit 1

VERSION=0.2

MAXITERS=${MAXITERS:-5}
LATEX=${LATEX:-latex}
BIBTEX=${BIBTEX:-bibtex}
IEEE_COPYOUT_LOG=${LOG:-ieee-copyout.log}

SED_FILE=ieee-copyout.sed.$$$$
if [ -f $SED_FILE ]; the
    rm -f $SED_FILE
fi

sep="------------------------------------"

while test -n "$1"
do
	case "$1"
	in

	--clean)
		if [ -f $IEEE_COPYOUT_LOG ]; then
		    rm -f $IEEE_COPYOUT_LOG
		fi
		exit 0
		;;

	--version)
		echo "ieee-copyout version $VERSION (part of LaTeX-Mk)"
		exit 0
		;;

	-*)
		echo "unknown option: $1"
		exit 1
		;;

	*)
		break
		;;

	esac
done

INFILE=$1

if test -z "$INFILE" ; then
	echo "$0:   You must specify an input file"
	exit 1
fi

if test ! -f "${INFILE}" ; then
    INFILE=${INFILE}.tex
fi
if test ! -f "${INFILE}" ; then
	echo "$0:   Neither ${INFILE} nor ${INFILE}.tex exists"
	exit 1
fi
NAME=`basename ${INFILE} .tex`


$ndir=/tmp/foo
rm -f $ndir/*
if [ ! -d $ndir ]; then
    mkdir -p $ndir
fi

echo Processing figures
i=1
for f in `awk 'BEGIN{FS="[{}]+";} /^\\includegraphics/ {print $2;}' ${NAME}.tex`
do

    nf=fig${i}.eps
    echo "Renaming $f to $nf"
    echo "s;{$f};{$nf};g" >> $SED_FILE
    cp $f $ndir/$nf

    i=`expr $i + 1`
done

set -x
sed -f $SED_FILE $tf | awk '/@docstart@/,/@bibstart@/ {print}' > $ndir/${ntf}.tex
cat jssc_autocal.bbl >> $ndir/${ntf}.tex
sed -f $SED_FILE $tf | awk '/@bibend@/,/@docend@/ {print}' >> $ndir/${ntf}.tex
cp IEEEtran.cls $ndir

cat > $ndir/README.txt <<EOF

EOF
exit 0

