## Copyright (c) 2006, 2007, 2010, 2011, 2024 Dan McMahill
## All rights reserved.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; version 2 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

check_DATA=	${GOLDEN_FILES}

DISTCLEANFILES=	${LOG_FILES} ${DLOG_FILES} ${PROCESSED_REF_FILES} ${PROCESSED_LOG_FILES}
CLEANFILES=	${LOG_FILES} ${DLOG_FILES} ${PROCESSED_REF_FILES} ${PROCESSED_LOG_FILES}

EXTRA_DIST=	${GOLDEN_FILES}
LOG_FILES=	${GOLDEN_FILES:.ref=.log}
DLOG_FILES=	${GOLDEN_FILES:.ref=.dlog}
PROCESSED_REF_FILES=	${GOLDEN_FILES:.ref=-processed.ref}
PROCESSED_LOG_FILES=	${GOLDEN_FILES:.ref=-processed.log}

GOLDEN_FILES=	\
	basic_space1.ref \
	basic1.ref \
	basic2.ref \
	basic3.ref \
	basic4.ref \
	bibtex1.ref \
	bibtex2.ref \
	bibtex3.ref \
	bibtex4.ref \
	bibtex5.ref \
	bibtex6.ref \
	bibunits1.ref \
	bibunits2.ref \
	bibunits3.ref \
	bibunits4.ref \
	bibunits5.ref \
	bibunits6.ref \
	bibunits7.ref \
	bibunits8.ref \
	makegls1.ref \
	makeindex1.ref \
	makeindex2.ref \
	makeindex3.ref \
	makeindex4.ref \
	pdf1.ref \
	pdf2.ref \
	pdf3.ref \
	pdf4.ref \
	vars1.ref \
	vars2.ref \
	vars3.ref \
	vars4.ref \
	vars5.ref \
	vars6.ref \
	vars7.ref


