name: latex-mk CI - MacOS

on:
  push:
    paths-ignore:
      - .github/workflows/ci-linux.yml
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - .github/workflows/ci-linux.yml
  # Allows you to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
             brew update
             brew install autoconf
             brew install automake
             brew install bmake
             brew install gettext
             brew install ghostscript
             brew install texlive
             brew install latex2html
             brew install hevea
             brew install texinfo
             brew install texi2html
             brew install tgif
             brew install tcsh
             brew install ksh93

      - name: Autogen
        run: ./autogen.sh

      - name: Configure
        run: ./configure

      - name: Build
        run: |
          make

      - name: Check
        run: |
          make check

      - name: Upload Test Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: testsuite-log
          path: testsuite/test-suite.log

      - name: Display Test Output
        if: failure()
        run: ./ci/failures.sh

      - name: Distcheck
        run:  |
          make distcheck

      # TODO: re-enable without depending on exact version
      # - name: Upload Tarball
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: latex-mk-2.1A
      #     path: latex-mk-2.1A.tar.gz
